version: '3.5'
services:
  frontend:
    image: princemargaret/frontend
    ports:
      - "3000:3000"
        
  

  authentication:
    image: princemargaret/authentication
    ports:
      - 8000:8000
  
  googleauth:
    image: princemargaret/googleauth
    ports:
      - 5000:5000

  likedapi:
    image: princemargaret/likedapi
    ports:
      - 6000:6000

  muzixcloud:
    image: princemargaret/muzixcloud
    ports:
      - 7000:7000
  
  playlist:
    image: princemargaret/playlist
    ports:
      - 9000:9000

